### PR TITLE
Fix Duplicate DPaths & Deterministic Modal Improvements

### LINKED ISSUE #1563: Duplicate entries in deriviation path
### Description of the Issue

When selecting the deriviation path dropdown in the DeterministicWalletModal, duplicate entries can appear

### Steps to Reproduce

1. Get to DeterministicWalletModal component via View & Send -> Ledger
2. Click on deriviation path dropdown
3. Multiple Ledger(ETH) entries appear

### Console Logs / Screenshots

(Console logs or screenshots go here, if applicable)

2018-04-17-184254_647x218_scrot
2018-04-17-184248_647x205_scrot

### PR DESCRIPTION
**Pull request by wbobeirne**
Closes #1563

### Description

Removes duplicate dpaths, and treats each option as a unique option rather than always selecting the first instance of the dpath. Also made some quick improvements to the modal while I was here.

### Changes

* Fixes de-duplication in the dpaths selector function
* Pass around full `DPath` objects to wallet decrypt components & deterministic modal, rather than just the dpath string.
    * This makes it so that if you select `Default (POA)`, that it shows up as the selected option, whereas before it would should `Default (ETH)` since they have the same dPath, and ETH is the first in the list.
* Improve deterministic wallet modal UI
    * When no token is selected, show small, light `N/A` text instead of `???`
    * Token balances now show spinner while loading
    * Gets rid of constantly persistent scrollbar on table, even though it doesn't scroll

### Steps to Test

1. Enter a mnemonic, ensure there are no duplicate dPaths and it functions correctly
2. Unlock a TREZOR, ensure there are no duplicate dPaths and it functions correctly
3. Unlock a Ledger, ensure there are no duplicate dPaths and it functions correctly

### Screenshots

screen shot 2018-04-26 at 12 07 49 pm

### CODE REVIEW

**Comment by HenryNguyen5** [comment]
This also closes https://github.com/MyCryptoHQ/MyCrypto/issues/1570

File: common/components/WalletDecrypt/components/DeterministicWalletsModal.tsx [hunk 1]
```diff
@@ -42,11 +42,11 @@ interface Props {
 
   onCancel(): void;
   onConfirmAddress(address: string, addressIndex: number): void;
-  onPathChange(path: string): void;
+  onPathChange(dPath: DPath): void;
 }
 
 interface State {
-  currentLabel: string;
+  currentDPath: DPath;
```
Comment (HenryNguyen5) [inline common/components/WalletDecrypt/components/DeterministicWalletsModal.tsx]: This seems like an invalid type since if the user uses a custom dpath, it's not in our enumeration of dpaths.

**Comment by dternyak** [comment]
👍 Can confirm no duplicate dpath options.

File: common/components/WalletDecrypt/components/DeterministicWalletsModal.tsx (hunk 1 above)
Comment (wbobeirne) [reply common/components/WalletDecrypt/components/DeterministicWalletsModal.tsx]: `DPath` isn't an enum, it's just an interface. So it's OK if it's not one of our hardcoded ones.
