### PR TITLE
Fix Ledger DPaths, Improve Error Messaging

### LINKED ISSUE #1515: Can't connect to Ledger on testnets, "Invalid status 6804"
### Description of the Issue

Attempting to unlock a Ledger on Ropsten results in the following error:

> Invalid status 6804

I can reproduce in dev, and on beta.mycrypto.com

### Steps to Reproduce

1. Switch to Ropsten network (Or any other testnet)
2. Attempt to unlock Ledger

### PR DESCRIPTION
**Pull request by wbobeirne**
Closes #1515

### Description

Ledger's dpaths were all out of sync with what is in production. This PR fixes that, as well as improves some error messaging.

### Changes

* Fixed all dpaths to match production config
* Added exception to dpath validation for ETC Ledger
* Provided human readable error messages for common Ledger issues
* Added network name to tip since UBQ and EXP have their own Ledger apps (Used to say "ethereum app" all the time.)
* Fixed issue with `.alert` elements having an invisible element that covered other stuff

### Steps to Test

1. Open up this branch and mycrypto.com in side by side tabs
2. Connect to each network on both with a Ledger, confirm addresses are the same
    * If it errors for some reason, confirm it errors the same on both

### CODE REVIEW

File: common/config/dpaths.ts [hunk 1]
```diff
@@ -86,5 +86,5 @@ export const EXTRA_PATHS = [ETH_SINGULAR];
 
 // whitespace strings are evaluated the same way as nospace strings, except they allow optional spaces between each portion of the string
 // ie. "m / 44' / 0' / 0'" is valid, "m / 4 4' / 0' / 0'" is invalid
-export const dPathRegex = /m\/(44|0)'\/[0-9]+\'\/[0-9]+(\'+$|\'+(\/[0-1]+$))/;
+export const dPathRegex = /m\/44'\/[0-9]+\'\/[0-9]+(\'+$|\'+(\/[0-1]+$))/;
```
Comment (dternyak) [inline common/config/dpaths.ts]: I'd be interested in understanding why we allowed `0` as the path element before.

Comment (dternyak) [reply common/config/dpaths.ts]: Reminder: check SingularDTV

Comment (wbobeirne) [reply common/config/dpaths.ts]: Yep, it was singular dtv. I thought rather than keep manipulating this already very complex regex, and allow for more malformed dpaths, Id just add exceptions directly to the validator function.
