### PR TITLE
Forward query arguments during redirect

### LINKED ISSUE #968: Prefilled transaction is broken
Since the change from `/send-transaction` to `/account/send`, we lose the query parameters upon navigation. We'll need to find a way to carry over the data from the query.

### PR DESCRIPTION
**Pull request by aitrean**
Closes #968 

Copy search arguments on router redirects to preserve prefilled transaction queries.

### CODE REVIEW

**Comment by dternyak** [comment]
A more generic solution might be valuable so that this isn't implemented only for the `send-transaction` redirect.

I know that custom networks are at least one other instance where we might want pre-filled fields via query params.

File: common/Root.tsx [hunk 1]
```diff
@@ -95,7 +95,7 @@ export default class Root extends Component<Props, State> {
 
 const LegacyRoutes = withRouter(props => {
   const { history } = props;
-  const { pathname, hash } = props.location;
+  const { pathname, hash, search } = props.location;
 
   if (pathname === '/') {
     switch (hash) {
```
Comment (wbobeirne) [inline common/Root.tsx]: Search carry-over needs to happen for `#send-transaction` and `#offline-transaction` too.

**Comment by dternyak** [comment]
@wbobeirne Mind re-reviewing when you have a chance?
